branches:
  except:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
dist: xenial
env:
- OS=alpine_3.10
- OS=alpine_3.3
- OS=alpine_3.4
- OS=alpine_3.5
- OS=alpine_3.6
- OS=alpine_3.7
- OS=alpine_3.8
- OS=alpine_3.9
- OS=alpine_edge
- OS=archlinux_latest
- OS=centos_7
- OS=centos_8
- OS=debian_buster
- OS=debian_jessie
- OS=debian_stretch
- OS=fedora_23
- OS=fedora_24
- OS=fedora_25
- OS=fedora_26
- OS=fedora_27
- OS=fedora_28
- OS=fedora_29
- OS=fedora_30
- OS=fedora_31
- OS=fedora_32
- OS=ubi8_8.0
- OS=ubuntu_xenial
- OS=ubuntu_bionic
language: python
python: 3.7
script:
- ansible-galaxy-local-deps-write
- dcb --upstreamgroup andrewrothstein --upstreamapp docker-ansible-role --pull ${OS}
  --write ${OS} --build ${OS} --push ${OS}
services:
- docker
sudo: required
