---
- name: Testing andrewrothstein.k3d
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'k3d --version'
      ansible.builtin.command: /usr/local/bin/k3d --version
      changed_when: false
      register: k3d_test_output
    - name: Output from 'k3d --version'
      ansible.builtin.debug:
        msg: '{{ k3d_test_output.stdout }}'
